name: starter_template_get_x
description: Put your description here
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.3.0 # log events in clear way instead of (print)
  uuid: ^4.5.0 # To get unique ID

  get: ^4.6.6 # state management package
  get_storage:
  dio: ^5.4.3+1 # package used for api calling
  pretty_dio_logger: ^1.3.1 # logger to print api requests

  shared_preferences: ^2.2.3 # shared preferences persistence key value store

  json_annotation: ^4.8.1 # helper package for json code generation with json serializable

  flutter_svg:

  firebase_core: ^3.0.0 # to initialize firebase services
  firebase_messaging: ^15.0.0 # fcm services
  awesome_notifications: ^0.9.3+1 # notifications services (will be used for fcm)

  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: 1.4.0 # rename app

  google_fonts: ^6.2.1 # google font library

  dropdown_button2: ^2.3.9 # drop down menu
  #  flutter_stripe: ^11.0.0 # Stripe Payment Gateway
  flutter_cashfree_pg_sdk: ^2.1.3+33 # Cash free payment integration package

  sqflite: # Local database

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1 # package used to generate toJson and fromJson
  flutter_gen_runner:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/images/
    - assets/logo/
    - assets/svg/
    - assets/google_fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen: # This setting generate assets(svg, png etc), colors,
  output: lib/config/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/color/colors.xml